name: mongodb
icon: mongodb
type: database
title: MongoDB
hostname: mongodb
containers:
- name: mongodb
  image: bitnami/mongodb
  env:
  - name: DISABLE_WELCOME_MESSAGE
    value: 'true'    
options:
- version: '7.0'
  tag: 7.0.14-debian-12-r3
endpoints:
- name: mongodb
  ports:
  - name: mongodb
    number: 27017
    type: tcp
labels:
- mongodb

volumes:
- name: data
  title: Data
  optional: true
  helm: 
    values:
    - name: persistence.enabled
      value: true
    - name: persistence.size
      value: '{{volumes.data.size}}Gi'
    # mandatory to use existing claim since this volume will have import function
    # we will mount different claim after import and doing it through sts's volumeclaimtemplates is not supported
    - name: persistence.existingClaim
      value: '{{volumes.data.claim}}'

tokens:
- name: password
  generate:
    regex: '[0-9a-z-]{32}'

database:
  type: mongodb
  kind: mongodb
  port: 27017
  ssl: true
  root:
    username: root
    password: '{{password}}'    

helm:
  name: bitnami
  source: oci://registry-1.docker.io/bitnamicharts/mongodb
  chart: oci://registry-1.docker.io/bitnamicharts/mongodb
  version: 15.6.25
  configurations:
  - container: mongodb
    labels: commonLabels
    annotations: commonAnnotations
    env: extraEnvVars
    resources: resources
  values:
  - name: auth.rootPassword
    value: '{{password}}'
  - name: resourcesPreset
    value: 'none'
  - name: architecture
    value: 'standalone'
  - name: persistence.enabled    
    value: false
